### ISSUE TITLE
Please add ip_vs module as a prerequisites

### ISSUE THREAD

**Issue by servicemeshistio** [gyliu513/work#6]
Hi Guang

I was getting CrashLoopBackOff for vip manager when I deployed your keepalived helm chart from https://github.com/gyliu513/work/tree/master/k8s/charts/keepalived/chart/keepalived

Can you please add this in the README?

## Prerequisites

`ipvs` module is required by the vip manager.

Make sure that the ip_vs module is loaded.

```
# lsmod| grep ^ip_vs
```

If no `ip_vs` module is loaded, install `ipvsadm`

```console
# yum -y install ipvsadm

# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn

# lsmod | grep ^ip_vs
ip_vs                 145497  0
```

Sorry - I should have created a PR. Thank YOU.

**Comment by gyliu513** [comment]
Thanks @servicemeshistio for pointing this out, the README was updated at https://github.com/gyliu513/work/blob/master/k8s/charts/keepalived/chart/keepalived/README.md , any more comments or suggestions are welcomed !! ;-)
